CREATE TABLE IF NOT EXISTS maxacali (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  cd_setor VARCHAR(100) NOT NULL,
  situacao VARCHAR(20) NULL,
  cd_sit TINYINT NULL,
  cd_tipo TINYINT NULL,
  area_km2 DECIMAL(12,7) NULL,
  cd_regiao TINYINT NULL,
  nm_regiao VARCHAR(50) NULL,
  cd_uf SMALLINT NULL,
  nm_uf VARCHAR(100) NULL,
  cd_mun INT NULL,
  nm_mun VARCHAR(150) NULL,
  cd_dist BIGINT NULL,
  nm_dist VARCHAR(150) NULL,
  cd_subdist BIGINT NULL,
  nm_subdist VARCHAR(150) NULL,
  cd_bairro BIGINT NULL,
  nm_bairro VARCHAR(150) NULL,
  cd_nu VARCHAR(30) NULL,
  nm_nu VARCHAR(150) NULL,
  cd_fcu VARCHAR(30) NULL,
  nm_fcu VARCHAR(150) NULL,
  cd_aglom VARCHAR(30) NULL,
  nm_aglom VARCHAR(150) NULL,
  cd_rgint INT NULL,
  nm_rgint VARCHAR(150) NULL,
  cd_rgi INT NULL,
  nm_rgi VARCHAR(150) NULL,
  cd_concurb VARCHAR(30) NULL,
  nm_concurb VARCHAR(150) NULL,
  v0001 INT NULL,
  v0002 INT NULL,
  v0003 INT NULL,
  v0004 INT NULL,
  v0005 DECIMAL(6,2) NULL,
  v0006 DECIMAL(12,4) NULL,
  v0007 INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_maxakali_setores_cd_setor (cd_setor),
  KEY idx_maxakali_setores_cd_mun (cd_mun),
  KEY idx_maxakali_setores_cd_uf (cd_uf)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
