SELECT
    COUNT(1) AS total_registros
FROM paciente p
WHERE UPPER(TRIM(p.DS_CID)) IN (
    'BRONQUIOLITE AGUDA',
    'BRONQUIOLITE AGUDA DEVIDA A VIRUS SINCICIAL RESPIRATORIO',
    'BRONQUIOLITE AGUDA DEVIDA A OUTROS MICROORGANISMOS ESPECIFICADOS'
)
  AND p.DT_ATENDIMENTO BETWEEN '2022-01-01' AND '2022-12-31';
