SELECT
    COUNT(1) AS total_registros
FROM paciente p
WHERE UPPER(TRIM(p.DS_CID)) IN (
    'INFECCOES AGUDAS DAS VIAS AEREAS SUPERIORES DE LOCALIZACOES MULTIPLAS E NAO ESPECIFICADAS',
    'INFECCAO AGUDA DAS VIAS AEREAS SUPERIORES NAO ESPECIFICADA',
    'INFECCOES AGUDAS NAO ESPECIFICADA DAS VIAS AEREAS INFERIORES'
)
  AND p.DT_ATENDIMENTO BETWEEN '2022-01-01' AND '2022-12-31';
